# ACPI Wakeup Persistd Configuration File
# Sources listed under [enabled] will be enabled.
# Sources listed under [disabled] will be disabled.
# Ignore cases where source is not present in /proc/acpi/wakeup.

# Use 'cat /proc/acpi/wakeup' to see available devices.

[enabled]
# Example: Enable USB ports
USB0
USB1
USB2
USB3
XHCI
# Example: Enable Lid switch
LID

[disabled]
# Example: Disable PCIe devices that wake up randomly
PXSX
LPC
# Example: Disable Wi-Fi
WLAN
# Example: Disable Power Button wake
PWRB
# Example: Disable RTC
RTC
